# Generated by Django 5.1.3 on 2024-12-31 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_company', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_color', models.CharField(max_length=20)),
                ('vehicle_owner', models.CharField(max_length=20)),
                ('vehicle_owner_contact', models.CharField(max_length=20)),
                ('vehicle_owner_address', models.CharField(max_length=20)),
                ('vehicle_owner_email', models.CharField(max_length=20)),
                ('vehicle_owner_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('parking_charge', models.FloatField()),
                ('parking_slot', models.CharField(max_length=20)),
                ('parking_lot', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='history_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parking.vehicle')),
            ],
        ),
    ]
